name: trip_manager
description: "mobile application which is used to  manage all the procces throungh one application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.0
  equatable: ^2.0.5
  file_picker: ^7.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.5
  flutter_dotenv: ^5.1.0
  flutter_esc_pos_network: ^1.0.3
  flutter_esc_pos_utils: ^1.0.1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  lottie: ^3.1.2



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
